from news_source import NewsSource

newsSources = [
    NewsSource("NOS","https://feeds.nos.nl/nosnieuwsalgemeen","Algemeen Nieuws"),
    NewsSource("Nieuwsblad","https://www.nieuwsblad.nl/rss/nieuws","Algemeen Nieuws"),
    NewsSource("Nu.nl","https://www.nu.nl/rss/Algemeen","Algemeen Nieuws"),
    NewsSource("NRC","https://www.nrc.nl/rss","Algemeen Nieuws"),
    NewsSource("Tweakers","https://tweakers.net/feeds/mixed.xml","Technologie"),
    NewsSource("AD","https://www.ad.nl/nieuws/rss.xml","Algemeen Nieuws"),
    NewsSource("NRC","https://www.nrc.nl/rss","Algemeen Nieuws"),
    NewsSource("SlowTest","https://fakeresponder.com/?sleep=50000000000","Development App Test"),
    NewsSource("Verge","https://www.theverge.com/rss/index.xml","Technologie, Engels"),
    NewsSource("TechCrunch","https://techcrunch.com/feed/","Technologie, Engels"),
    NewsSource("Rijksoverheid nieuws", "https://feeds.rijksoverheid.nl/nieuws.rss", "Overheid"),
    NewsSource("RIVM nieuws", "https://www.rivm.nl/nieuws/rss.xml", "Overheid"),
    NewsSource("Politie nieuws", "https://rss.politie.nl/rss/algemeen/ab/algemeen.xml", "Overheid"),
    NewsSource("Nieuws van de regering", "https://feeds.rijksoverheid.nl/regering/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de ministerie", "https://feeds.rijksoverheid.nl/ministeries/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de ministerraad", "https://feeds.rijksoverheid.nl/regering/ministerraad/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Algemene Zaken","https://feeds.rijksoverheid.nl/ministeries/ministerie-van-algemene-zaken/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van asiel en migratie","https://feeds.rijksoverheid.nl/ministeries/ministerie-van-asiel-en-migratie/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Cultureel Onderwijs","https://feeds.rijksoverheid.nl/ministeries/ministerie-van-cultureel-onderwijs/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Binnenlandse Zaken en Koninkrijksrelaties","https://feeds.rijksoverheid.nl/ministeries/ministerie-van-binnenlandse-zaken-en-koninkrijksrelaties/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Buitenlandse Zaken","https://feeds.rijksoverheid.nl/ministeries/ministerie-van-buitenlandse-zaken/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Defensie","https://feeds.rijksoverheid.nl/ministeries/ministerie-van-defensie/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Economische Zaken","https://feeds.rijksoverheid.nl/ministeries/ministerie-van-economische-zaken/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Financiën","https://feeds.rijksoverheid.nl/ministeries/ministerie-van-financien/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Justitie","https://feeds.rijksoverheid.nl/ministeries/ministerie-van-justitie/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Infrastructuur en Waterstaat", "https://feeds.rijksoverheid.nl/ministeries/ministerie-van-infrastructuur-en-waterstaat/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Justitie en Veiligheid","https://feeds.rijksoverheid.nl/ministeries/ministerie-van-justitie-en-veiligheid/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Klimaat en Groene Groei","https://feeds.rijksoverheid.nl/ministeries/ministerie-van-klimaat-en-groene-groei/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Landbouw, Visserij, Voedselzekerheid en Natuur","https://www.rijksoverheid.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%2C%7B%22field%22%3A%22ministry%22%2C%22values%22%3A%5B%22Ministerie%20van%20Landbouw%2C%20Visserij%2C%20Voedselzekerheid%20en%20Natuur%22%5D%2C%22type%22%3A%22all%22%7D%5D%2C%22resultSearchTerm%22%3A%22%22%7D", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Onderwijs, Cultuur en Wetenschap","https://feeds.rijksoverheid.nl/ministeries/ministerie-van-onderwijs-cultuur-en-wetenschap/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Sociale Zaken en Werkgelegenheid", "https://feeds.rijksoverheid.nl/ministeries/ministerie-van-sociale-zaken-en-werkgelegenheid/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Volksgezondheid, Welzijn en Sport","https://feeds.rijksoverheid.nl/ministeries/ministerie-van-volksgezondheid-welzijn-en-sport/nieuws.rss", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Volkshuisvesting en Ruimtelijke Ordening","https://feeds.rijksoverheid.nl/ministeries/ministerie-van-volkshuisvesting-en-ruimtelijke-ordening/nieuws.rss", "Overheid"),
    NewsSource("Alle besluiten gemaakt","https://feeds.rijksoverheid.nl/besluiten.rss", "Overheid"),
    NewsSource("Alle kamerstukken","https://feeds.rijksoverheid.nl/kamerstukken.rss", "Overheid"),
    NewsSource("Alle toespraken","https://feeds.rijksoverheid.nl/toespraken.rss", "Overheid"),
    NewsSource("Omroep Flevoland", "https://www.omroepflevoland.nl/RSS/rss.aspx", "Lokaal nieuws"),
    NewsSource("Omroep Gelderland", "https://www.omroepgelderland.nl/rss", "Lokaal nieuws"),
    NewsSource("Omroep West", "https://www.omroepwest.nl/rss/index.xml", "Lokaal nieuws"),
    NewsSource("Omroep Noord", "https://www.rtvnoord.nl/rss", "Lokaal nieuws"),
    NewsSource("Omroep Utrecht", "https://www.rtvutrecht.nl/rss/nieuws.xml", "Lokaal nieuws"),
    NewsSource("RTV Noord", "http://www.rtvnoord.nl/rss/rssnoordnieuws.xml", "Lokaal nieuws"),
    NewsSource("RTV Oost", "http://rss.rtvoost.nl/", "Lokaal nieuws"),
    NewsSource("RTV Zuid", "http://www.rtvzuid.nl/rss/rsszuidnieuws.xml", "Lokaal nieuws"),
    NewsSource("RTV Drenthe", "https://www.rtvdrenthe.nl/rss/index.xml", "Lokaal nieuws"),
    NewsSource("HV Almere", "http://hv-almere.nl/rss", "Lokaal nieuws"),
    NewsSource("Autoriteit Persoonsgegevens", "https://www.autoriteitpersoonsgegevens.nl/feed/article/rss.xml", "Toezichthouder, Privacy, AVG"),
    NewsSource("Telegraaf", "https://www.telegraaf.nl/rss", "Algemeen nieuws"),
    NewsSource("BNR", "https://static.bnr.nl/assets/bnr-next/rss/home.xml", "Algemeen nieuws"),
    NewsSource("Defensie", "https://feeds.defensie.nl/nieuws.rss", "Overheid, Defensie"),
    NewsSource("Marine", "https://feeds.defensie.nl/organisatie/marine/nieuws.rss", "Overheid, Defensie"),
    NewsSource("Landmacht", "https://feeds.defensie.nl/organisatie/landmacht/nieuws.rss", "Overheid, Defensie"),
    NewsSource("Luchtmacht", "https://feeds.defensie.nl/organisatie/luchtmacht/nieuws.rss", "Overheid, Defensie"),
    NewsSource("Marechaussee", "https://feeds.defensie.nl/organisatie/marechaussee/nieuws.rss", "Overheid, Defensie"),
    NewsSource("CBS", "https://www.cbs.nl/nl-nl/rss-feeds/alles", "Overheid, Statistieken"),
    NewsSource("Rekenkamer", "https://feeds.rekenkamer.nl/nieuws.rss", "Overheid"),
    NewsSource("KNMI", "https://www.knmi.nl/rssfeeds/rss_KNMInieuwsberichten", "Overheid, Weer"),
    NewsSource("Financieel dagblad", "https://fd.nl/?rss", "Financieel nieuws"),
    NewsSource("Reuters", "https://www.reutersagency.com/feed/?taxonomy=best-sectors&post_type=best", "Algemeen nieuws, Engels"),
    NewsSource("BBC", "https://feeds.bbci.co.uk/news/rss.xml", "Algemeen nieuws, Engels"),
    NewsSource("Google nieuws", "https://news.google.com/rss", "Algemeen nieuws")
]
