from news_source import NewsSource

newsSources = [
    NewsSource("AD","https://www.ad.nl/nieuws/rss.xml","Algemeen Nieuws"),
    # NewsSource("Ars technica apple", "https://feeds.arstechnica.com/arstechnica/apple", "Technologie, apple, Engels"),
    # NewsSource("Ars technica boardgames", "https://feeds.arstechnica.com/arstechnica/cardboard", "Engels, boardgames"),
    # NewsSource("Ars technica cars", "https://feeds.arstechnica.com/arstechnica/cars", "Technologie, Engels, cars"),
    # NewsSource("Ars technica featured", "https://feeds.arstechnica.com/arstechnica/features", "Technologie, Engels"),
    # NewsSource("Ars technica gadgets", "https://feeds.arstechnica.com/arstechnica/gadgets", "Technologie, Engels, gadgets"),
    # NewsSource("Ars technica gaming", "https://feeds.arstechnica.com/arstechnica/gaming", "Technologie, Engels, gaming"),
    # NewsSource("Ars technica science", "https://feeds.arstechnica.com/arstechnica/science", "Technologie, Engels, science"),
    # NewsSource("Ars technica staff", "https://feeds.arstechnica.com/arstechnica/staff-blogs", "Technologie, Engels, staff"),
    # NewsSource("Ars technica tech lab", "https://feeds.arstechnica.com/arstechnica/technology-lab", "Technologie, Engels, lab"),
    # NewsSource("Ars technica tech policy", "https://feeds.arstechnica.com/arstechnica/tech-policy", "Technologie,policy, Engels"),
    NewsSource("Ars technica", "https://feeds.arstechnica.com/arstechnica/index", "Technologie, Engels"),
    # NewsSource("arXiv Astrophysics", "https://rss.arxiv.org/rss/astro-ph", "Technologie, Engels, Astrophysics"),
    # NewsSource("arXiv Compute science", "https://rss.arxiv.org/rss/cs", "Technologie, Engels, Computer science"),
    # NewsSource("arXiv Condensed matter", "https://rss.arxiv.org/rss/cond-mat", "Technologie, Engels, Condensed matter"),
    # NewsSource("arXiv Economics", "https://rss.arxiv.org/rss/econ", "Technologie, Engels, Economics"),
    # NewsSource("arXiv Electrical engineering and system science", "https://rss.arxiv.org/rss/eess", "Technologie, Engels, Electrical engineering, system science"),
    # NewsSource("arXiv general relativity and quantum cosmology", "https://rss.arxiv.org/rss/gr-gq", "Technologie, Engels, General relativity, quantum cosmology"),
    # NewsSource("arXiv high energy - experiment", "https://rss.arxiv.org/rss/hep-ex", "Technologie, Engels, high energy, experiment"),
    # NewsSource("arXiv high energy physics - lattic", "https://rss.arxiv.org/rss/hep-lat", "Technologie, Engels, Astrophysics"),
    # NewsSource("arXiv high energy physics - phenomenology", "https://rss.arxiv.org/rss/hep-ph", "Technologie, Engels, Astrophysics"),
    # NewsSource("arXiv high energy physics - theory", "https://rss.arxiv.org/rss/hep-th", "Technologie, Engels, Astrophysics"),
    # NewsSource("arXiv mathematical physics", "https://rss.arxiv.org/rss/math-ph", "Technologie, Engels, Astrophysics"),
    # NewsSource("arXiv mathmatics", "https://rss.arxiv.org/rss/math", "Technologie, Engels, mathmatics"),
    # NewsSource("arXiv nonlinear sciences", "https://rss.arxiv.org/rss/nlin", "Technologie, Engels, Astrophysics"),
    # NewsSource("arXiv nuclear experiment", "https://rss.arxiv.org/rss/nucl-ex", "Technologie, Engels, nuclear, experiment"),
    # NewsSource("arXiv nuclear theory", "https://rss.arxiv.org/rss/nucl-th", "Technologie, Engels, nuclear, theory"),
    # NewsSource("arXiv physics", "https://rss.arxiv.org/rss/physics", "Technologie, Engels, Astrophysics"),
    # NewsSource("arXiv Quantitative Finance", "https://rss.arxiv.org/rss/q-fin", "Technologie, Engels, Astrophysics"),
    # NewsSource("arXiv Statistics", "https://rss.arxiv.org/rss/stat", "Technologie, Engels, Astrophysics"),
    NewsSource("Autoriteit Persoonsgegevens", "https://www.autoriteitpersoonsgegevens.nl/feed/article/rss.xml", "Toezichthouder, Privacy, AVG"),
    NewsSource("AWS Architecture Blog", "https://aws.amazon.com/blogs/architecture/feed/", "Technology, English, Cloud, Native"),
    NewsSource("BBC", "https://feeds.bbci.co.uk/news/rss.xml", "Algemeen nieuws, Engels"),
    NewsSource("BNR", "https://static.bnr.nl/assets/bnr-next/rss/home.xml", "Algemeen nieuws"),
    NewsSource("CBS", "https://www.cbs.nl/nl-nl/rss-feeds/alles", "Overheid, Statistieken"),
    NewsSource("Cloudflare Blog Native", "https://blog.cloudflare.com/rss/", "Technology, English, Cloud, Native"),
    NewsSource("Coding Horror (Jeff Atwood)", "https://blog.codinghorror.com/rss/", "Technology, English, Programming, Native"),
    NewsSource("Financieel dagblad", "https://fd.nl/?rss", "Financieel nieuws"),
    # NewsSource("Firstpost Arts and culture", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/art-and-culture.xml", "Arts, Culture, Engels"),
    # NewsSource("Firstpost Business", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/business.xml", "Business, Engels"),
    # NewsSource("Firstpost Education", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/education.xml", "Education, Engels"),
    # NewsSource("Firstpost Entertainment", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/entertainment.xml", "Entertainment, Engels"),
    # NewsSource("Firstpost Explainers", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/explainers.xml", "Explainers, Engels"),
    # NewsSource("Firstpost First Cricket", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/firstcricket.xml", "Sports, Engels"),
    # NewsSource("Firstpost Health", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/health.xml", "Health, Engels"),
    # NewsSource("Firstpost India", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/india.xml", "India, Engels"),
    # NewsSource("Firstpost Living", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/living.xml", "Living, Engels"),
    # NewsSource("Firstpost Opinion", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/opinion.xml", "Opinion, Engels"),
    # NewsSource("Firstpost Photos", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/photos.xml", "Photos, Engels"),
    # NewsSource("Firstpost Politics", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/politics.xml", "Politics, Engels"),
    # NewsSource("Firstpost Sports", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/sports.xml", "Sports, Engels"),
    # NewsSource("Firstpost Web stories", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/web-stories.xml", "Web stories, Engels"),
    # NewsSource("Firstpost World", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/world.xml", "World, Engels"),
    NewsSource("GitHub Blog Native", "https://github.blog/feed/", "Technology, English, Programming, Native"),
    NewsSource("Joel on Software", "https://www.joelonsoftware.com/feed/", "Technology, English, Culture, Native"),
    NewsSource("KNMI", "https://www.knmi.nl/rssfeeds/rss_KNMInieuwsberichten", "Overheid, Weer"),
    NewsSource("Nieuws van de Ministerie van Algemene Zaken","https://www.rijksoverheid.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%2C%7B%22field%22%3A%22ministry%22%2C%22values%22%3A%5B%22Ministerie%20van%20Algemene%20Zaken%22%5D%2C%22type%22%3A%22all%22%2C%22persistent%22%3Afalse%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Binnenlandse Zaken en Koninkrijksrelaties","https://www.rijksoverheid.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%2C%7B%22field%22%3A%22ministry%22%2C%22values%22%3A%5B%22Ministerie%20van%20Binnenlandse%20Zaken%20en%20Koninkrijksrelaties%22%5D%2C%22type%22%3A%22all%22%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Buitenlandse Zaken","https://www.rijksoverheid.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%2C%7B%22field%22%3A%22ministry%22%2C%22values%22%3A%5B%22Ministerie%20van%20Buitenlandse%20Zaken%22%5D%2C%22type%22%3A%22all%22%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Cultureel Onderwijs","https://www.rijksoverheid.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%2C%7B%22field%22%3A%22ministry%22%2C%22values%22%3A%5B%22Ministerie%20van%20Onderwijs%2C%20Cultuur%20en%20Wetenschap%22%5D%2C%22type%22%3A%22all%22%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Defensie","https://www.defensie.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Economische Zaken","https://www.rijksoverheid.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%2C%7B%22field%22%3A%22ministry%22%2C%22values%22%3A%5B%22Ministerie%20van%20Economische%20Zaken%20en%20Klimaat%22%5D%2C%22type%22%3A%22all%22%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Financiën","https://www.rijksoverheid.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%2C%7B%22field%22%3A%22ministry%22%2C%22values%22%3A%5B%22Ministerie%20van%20Financi%C3%ABn%22%5D%2C%22type%22%3A%22all%22%2C%22persistent%22%3Afalse%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Infrastructuur en Waterstaat", "https://www.rijksoverheid.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%2C%7B%22field%22%3A%22ministry%22%2C%22values%22%3A%5B%22Ministerie%20van%20Infrastructuur%20en%20Waterstaat%22%5D%2C%22type%22%3A%22all%22%2C%22persistent%22%3Afalse%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Justitie en Veiligheid","https://www.rijksoverheid.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%2C%7B%22field%22%3A%22ministry%22%2C%22values%22%3A%5B%22Ministerie%20van%20Justitie%20en%20Veiligheid%22%5D%2C%22type%22%3A%22all%22%2C%22persistent%22%3Afalse%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Klimaat en Groene Groei","https://www.rijksoverheid.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%2C%7B%22field%22%3A%22ministry%22%2C%22values%22%3A%5B%22Ministerie%20van%20Economische%20Zaken%20en%20Klimaat%22%5D%2C%22type%22%3A%22all%22%2C%22persistent%22%3Afalse%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Landbouw, Visserij, Voedselzekerheid en Natuur","https://www.rijksoverheid.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%2C%7B%22field%22%3A%22ministry%22%2C%22values%22%3A%5B%22Ministerie%20van%20Landbouw%2C%20Visserij%2C%20Voedselzekerheid%20en%20Natuur%22%5D%2C%22type%22%3A%22all%22%7D%5D%2C%22resultSearchTerm%22%3A%22%22%7D", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Onderwijs, Cultuur en Wetenschap","https://www.rijksoverheid.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%2C%7B%22field%22%3A%22ministry%22%2C%22values%22%3A%5B%22Ministerie%20van%20Onderwijs%2C%20Cultuur%20en%20Wetenschap%22%5D%2C%22type%22%3A%22all%22%2C%22persistent%22%3Afalse%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Sociale Zaken en Werkgelegenheid", "https://www.rijksoverheid.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%2C%7B%22field%22%3A%22ministry%22%2C%22values%22%3A%5B%22Ministerie%20van%20Sociale%20Zaken%20en%20Werkgelegenheid%22%5D%2C%22type%22%3A%22all%22%2C%22persistent%22%3Afalse%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Volksgezondheid, Welzijn en Sport","https://www.rijksoverheid.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%2C%7B%22field%22%3A%22ministry%22%2C%22values%22%3A%5B%22Ministerie%20van%20Volksgezondheid%2C%20Welzijn%20en%20Sport%22%5D%2C%22type%22%3A%22all%22%2C%22persistent%22%3Afalse%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("Nieuws van de Ministerie van Volkshuisvesting en Ruimtelijke Ordening","https://www.volkshuisvestingnederland.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("Nieuws van de ministerie", "https://www.rijksoverheid.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("NOS","https://feeds.nos.nl/nosnieuwsalgemeen","Algemeen Nieuws"),
    NewsSource("NRC","https://www.nrc.nl/rss","Algemeen Nieuws"),
    NewsSource("Nu.nl","https://www.nu.nl/rss/Algemeen","Algemeen Nieuws"),
    NewsSource("Omroep Flevoland", "https://www.omroepflevoland.nl/RSS/rss.aspx", "Lokaal nieuws"),
    NewsSource("Omroep Gelderland", "https://www.omroepgelderland.nl/rss", "Lokaal nieuws"),
    NewsSource("Omroep Noord", "https://www.rtvnoord.nl/rss", "Lokaal nieuws"),
    NewsSource("Omroep Utrecht", "https://www.rtvutrecht.nl/rss/nieuws.xml", "Lokaal nieuws"),
    NewsSource("Omroep West", "https://www.omroepwest.nl/rss/index.xml", "Lokaal nieuws"),
    NewsSource("Overreacted (Dan Abramov)", "https://overreacted.io/rss.xml", "Technology, English, Frontend, Native"),
    NewsSource("Politie nieuws", "https://rss.politie.nl/rss/algemeen/ab/algemeen.xml", "Overheid"),
    NewsSource("Rekenkamer", "https://www.rekenkamer.nl/api/rss?query=%7B%22filters%22%3A%5B%7B%22field%22%3A%22content_type%22%2C%22values%22%3A%5B%22pro%3AnewsDocument%22%5D%2C%22type%22%3A%22all%22%7D%5D%2C%22resultSearchTerm%22%3A%22%22%2C%22pageTitle%22%3A%22Nieuws%22%7D", "Overheid"),
    NewsSource("Reuters", "https://ir.thomsonreuters.com/rss/news-releases.xml", "Financieel nieuws, Engels"),
    NewsSource("Reuters", "https://www.reutersagency.com/feed/?taxonomy=best-sectors&post_type=best", "Algemeen nieuws, Engels"),
    NewsSource("RIVM nieuws", "https://www.rivm.nl/nieuws/rss.xml", "Overheid"),
    NewsSource("RTV Drenthe", "https://www.rtvdrenthe.nl/rss/index.xml", "Lokaal nieuws"),
    NewsSource("RTV Noord", "http://www.rtvnoord.nl/rss/rssnoordnieuws.xml", "Lokaal nieuws"),
    NewsSource("RTV Oost", "http://rss.rtvoost.nl/", "Lokaal nieuws"),
    NewsSource("RTV Zuid", "http://www.rtvzuid.nl/rss/rsszuidnieuws.xml", "Lokaal nieuws"),
    NewsSource("TechCrunch","https://techcrunch.com/feed/","Technologie, Engels"),
    NewsSource("Techradar", "https://www.techradar.com/feeds.xml", "Technologie, Engels"),
    NewsSource("TechSpot forums", "https://www.techspot.com/community/forums/-/index.rss", "Technologie, Engels"),
    NewsSource("TechSpot News", "https://www.techspot.com/backend.xml", "Technologie, Engels"),
    NewsSource("TechSpot Reviews", "https://www.techspot.com/reviews.xml", "Technologie, Engels"),
    NewsSource("The New York Times", "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml", "Technologie, Engels"),
    NewsSource("Troy Hunt (Have I Been Pwned)", "https://www.troyhunt.com/rss/", "Security, English, Cyber, Native"),
    NewsSource("Tweakers","https://tweakers.net/feeds/mixed.xml","Technologie"),
    NewsSource("Uber Engineering Native", "https://www.uber.com/blog/engineering/rss/", "Technology, English, Engineering, Native"),
    NewsSource("Verge","https://www.theverge.com/rss/index.xml","Technologie, Engels"),
]
